### ISSUE TITLE
全键盘

### ISSUE THREAD

**Issue by rcj60560** [wuzhendev/android-xnumberkeyboard#3]
你好，我之前做了一个键盘，参考别人做的，我感觉你这个效果很好，请问能添加全键盘模块吗，学习一哈 @wuzhendev 谢谢！

**Comment by wuzhendev** [comment]
这个只支持数字键盘，全键盘与业务场景关联比较强，暂时不支持，可以参考 `res/xml/keyboard_number.xml` 自定义全键盘
